# MP2 Part 1 — commit retrieval for aamphone's 10 projects
Retrieves every commit for each assigned project from World of Code (WoC V2412) and writes `aamphone_project_summary.csv` (semicolon-separated: project_wocid; commit_sha1; author; time; commit message).

In [8]:
## WoC data (World of Code API, retrieved 2026-10-08)
Number of commits, number of distinct author strings, and min/max author time (Unix seconds, with the UTC date).

| Project | Commits | Authors | Min time | Max time |
|---|---|---|---|---|
| arviz-devs_arviz | 9,492 | 395 | 1438170670 (2015-07-29) | 1761135327 (2025-10-22) |
| clindatsci_dicomweb-python-client | 518 | 39 | 1521487507 (2018-03-19) | 1757491841 (2025-09-10) |
| peal_vole | 595 | 7 | 1395418492 (2014-03-21) | 1757678214 (2025-09-12) |
| nbara_python-meegkit | 479 | 45 | 1227075592 (2008-11-19) | 1775048948 (2026-04-01) |
| flyaflya_causact | 457 | 21 | 1524067862 (2018-04-18) | 1757705466 (2025-09-12) |
| geolytix_xyz | 15,306 | 65 | 1512569316 (2017-12-06) | 1762277501 (2025-11-04) |
| genouest_biomaj-download | 505 | 19 | 1472208351 (2016-08-26) | 1750133502 (2025-06-17) |
| pressio_pressio | 4,282 | 52 | 1525121445 (2018-04-30) | 1757514162 (2025-09-10) |
| kkondo1981_aglm | 366 | 6 | 1546232994 (2018-12-31) | 1746979099 (2025-05-11) |
| winvector_vtreat | 1,081 | 6 | 1407432287 (2014-08-07) | 1736461287 (2025-01-09) |

33,140 unique commit SHA1s were listed by `p2c`; 59 returned "Key … not found" from WoC's commit store, so 33,081 are in `aamphone_project_summary.csv`.

**Validation against GitHub.** WoC counts are much higher than GitHub's default-branch counts (e.g., arviz 9,492 vs 1,670 on `main`; geolytix_xyz 15,306 vs 6,217) because WoC's `p2c` includes commits from all branches and from forks it attributes to the project. Author counts are also inflated because the same person appears under several name/e-mail strings.

In [9]:
import sys
sys.path.insert(0, 'woc_pkg')  # the WoC client unpacked by the cell above
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd
import time

netid = 'aamphone'
woc = WocMapsRemote(base_url="https://worldofcode.org/api/")
# woc = WocMapsRemote(base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY")

# Assigned projects from net2prj.csv (netID == aamphone): WoC id -> GitHub URL
projects = {
    'arviz-devs_arviz': 'https://github.com/arviz-devs/arviz',
    'clindatsci_dicomweb-python-client': 'https://github.com/clindatsci/dicomweb-python-client',
    'peal_vole': 'https://github.com/peal/vole',
    'nbara_python-meegkit': 'https://github.com/nbara/python-meegkit',
    'flyaflya_causact': 'https://github.com/flyaflya/causact',
    'geolytix_xyz': 'https://github.com/GEOLYTIX/xyz',
    'genouest_biomaj-download': 'https://github.com/genouest/biomaj-download',
    'pressio_pressio': 'https://github.com/Pressio/pressio',
    'kkondo1981_aglm': 'https://github.com/kkondo1981/aglm',
    'winvector_vtreat': 'https://github.com/WinVector/vtreat',
}

## Step 1 — commit SHA1s per project (p2c map)

In [10]:
list_df_commits = []
for prj in projects:
    for attempt in range(3):
        try:
            commits = woc.get_values('p2c', prj)
            break
        except Exception as e:
            print(prj, 'attempt', attempt + 1, 'failed:', e)
            time.sleep(5)
    else:
        raise RuntimeError('Could not retrieve commits for ' + prj)
    d = pd.DataFrame(commits, columns=['sha1'])
    d['project'] = prj
    print(f'{prj}: {len(d)} commits')
    list_df_commits.append(d)
    time.sleep(1)

df = pd.concat(list_df_commits, ignore_index=True)
df.to_csv('df_commits.csv', index=False)  # saved so the SHA1 list need not be fetched again
df.groupby('project').size()

arviz-devs_arviz: 9515 commits
clindatsci_dicomweb-python-client: 518 commits
peal_vole: 595 commits
nbara_python-meegkit: 479 commits
flyaflya_causact: 457 commits
geolytix_xyz: 15306 commits
genouest_biomaj-download: 506 commits
pressio_pressio: 4284 commits
kkondo1981_aglm: 366 commits
winvector_vtreat: 1114 commits

project
arviz-devs_arviz                      9515
clindatsci_dicomweb-python-client      518
flyaflya_causact                       457
genouest_biomaj-download               506
geolytix_xyz                         15306
kkondo1981_aglm                        366
nbara_python-meegkit                   479
peal_vole                              595
pressio_pressio                       4284
winvector_vtreat                      1114
dtype: int64

## Step 2 — commit content in batches
Batches of 10 SHA1s (below the 50 limit) with a 1-second wait between requests. Failed batches are retried, and any SHA1 still missing is reported at the end.

In [11]:
# a commit can belong to several projects, so retrieve each unique SHA1 once
shas = df['sha1'].drop_duplicates().tolist()
chunks = [shas[x:x + 10] for x in range(0, len(shas), 10)]
commit_content = {}
failed = []

for chunk in tqdm(chunks):
    for attempt in range(3):
        try:
            res, err = woc.get_values_many('commit.tch', chunk)
            break
        except Exception as e:
            print('retrying after error:', e)
            time.sleep(5 * (attempt + 1))
    else:
        failed.extend(chunk)
        continue
    if err:
        print('Got Errors', err)
    for k, v in res.items():
        commit_content[k] = v[0]  # needed because of the internal implementation
    time.sleep(1)  # stay under the rate limit

missing = [s for s in shas if s not in commit_content]
print('retrieved', len(commit_content), 'of', len(shas), 'unique commits; missing:', len(missing))

  2%|▏         | 58/3314 [01:00<56:27,  1.04s/it]

Got Errors {'0ebb3eb1ab86750b2d8825500e818fe0d09c1cda': 'Key 0ebb3eb1ab86750b2d8825500e818fe0d09c1cda not found in /da5_fast/All.sha1c/commit_14.tch'}

  3%|▎         | 92/3314 [01:36<56:14,  1.05s/it]

Got Errors {'17dc14ed8122bbc869ab1b953f00b4e56921f00c': 'Key 17dc14ed8122bbc869ab1b953f00b4e56921f00c not found in /da5_fast/All.sha1c/commit_23.tch'}

  6%|▌         | 195/3314 [03:23<54:08,  1.04s/it]

Got Errors {'342f28ddee5da5b7841719b1c3b4830f6093ba9f': 'Key 342f28ddee5da5b7841719b1c3b4830f6093ba9f not found in /da5_fast/All.sha1c/commit_52.tch'}

  6%|▌         | 199/3314 [03:28<53:59,  1.04s/it]

Got Errors {'355efbd0910a8e1e56b3f6f634bc65b8642ea486': 'Key 355efbd0910a8e1e56b3f6f634bc65b8642ea486 not found in /da5_fast/All.sha1c/commit_53.tch'}

  7%|▋         | 236/3314 [04:06<53:22,  1.04s/it]

Got Errors {'3f935d4b0f8a19b8ae253d271b3eba79bbb8a4bf': 'Key 3f935d4b0f8a19b8ae253d271b3eba79bbb8a4bf not found in /da5_fast/All.sha1c/commit_63.tch'}

  7%|▋         | 240/3314 [04:10<53:16,  1.04s/it]

Got Errors {'40a2fbad424e5524b49d7dd297ae16edeaa6bc77': 'Key 40a2fbad424e5524b49d7dd297ae16edeaa6bc77 not found in /da5_fast/All.sha1c/commit_64.tch'}

  8%|▊         | 251/3314 [04:22<53:08,  1.04s/it]

Got Errors {'43c61640ef48f4cbd50b8bd018bcdb592f9ac507': 'Key 43c61640ef48f4cbd50b8bd018bcdb592f9ac507 not found in /da5_fast/All.sha1c/commit_67.tch'}

  8%|▊         | 278/3314 [04:50<52:34,  1.04s/it]

Got Errors {'4ac3c1c2ca7301532c753718ab07d9cf721f6c6c': 'Key 4ac3c1c2ca7301532c753718ab07d9cf721f6c6c not found in /da5_fast/All.sha1c/commit_74.tch'}

  9%|▉         | 301/3314 [05:14<52:16,  1.04s/it]

Got Errors {'50a4eeff425f0bd810a1cd3595455dba33bf59f9': 'Key 50a4eeff425f0bd810a1cd3595455dba33bf59f9 not found in /da5_fast/All.sha1c/commit_80.tch'}

 10%|▉         | 329/3314 [05:43<51:48,  1.04s/it]

Got Errors {'58bae8b13bc1ca8e01e3bc598b88b2e6738968c7': 'Key 58bae8b13bc1ca8e01e3bc598b88b2e6738968c7 not found in /da5_fast/All.sha1c/commit_88.tch'}

 10%|█         | 335/3314 [05:49<51:36,  1.04s/it]

Got Errors {'5a51aa77694eb99d3ccca1d51a2ffa2e8fc16ffe': 'Key 5a51aa77694eb99d3ccca1d51a2ffa2e8fc16ffe not found in /da5_fast/All.sha1c/commit_90.tch'}

 10%|█         | 337/3314 [05:51<51:33,  1.04s/it]

Got Errors {'5a9eaf59844ad7358104f4f44f2649480a382572': 'Key 5a9eaf59844ad7358104f4f44f2649480a382572 not found in /da5_fast/All.sha1c/commit_90.tch'}

 11%|█         | 369/3314 [06:25<52:07,  1.06s/it]

Got Errors {'6307bd6c027337ff815394ea1f8bd3b8e59eac7f': 'Key 6307bd6c027337ff815394ea1f8bd3b8e59eac7f not found in /da5_fast/All.sha1c/commit_99.tch'}

 13%|█▎        | 418/3314 [07:16<50:15,  1.04s/it]

Got Errors {'70697007c34015338f8121c572f039d5356b3654': 'Key 70697007c34015338f8121c572f039d5356b3654 not found in /da5_fast/All.sha1c/commit_112.tch'}

 16%|█▌        | 514/3314 [08:56<48:34,  1.04s/it]

Got Errors {'8ab961478fdfb0f1fc8f48d4f8d82e1e0098cf36': 'Key 8ab961478fdfb0f1fc8f48d4f8d82e1e0098cf36 not found in /da5_fast/All.sha1c/commit_10.tch'}

 16%|█▌        | 517/3314 [08:59<48:31,  1.04s/it]

Got Errors {'8b9683a195be4fa8d5b574c29253cc177905fd0d': 'Key 8b9683a195be4fa8d5b574c29253cc177905fd0d not found in /da5_fast/All.sha1c/commit_11.tch'}

 20%|█▉        | 657/3314 [11:25<46:04,  1.04s/it]

Got Errors {'b0dc8fe138201a67581dd412a4d5c1e7846afd02': 'Key b0dc8fe138201a67581dd412a4d5c1e7846afd02 not found in /da5_fast/All.sha1c/commit_48.tch'}

 22%|██▏       | 731/3314 [12:42<44:53,  1.04s/it]

Got Errors {'c50a93fc0a37a17ec9ec3cb1f5a155bbab977df5': 'Key c50a93fc0a37a17ec9ec3cb1f5a155bbab977df5 not found in /da5_fast/All.sha1c/commit_69.tch'}

 22%|██▏       | 734/3314 [12:45<44:51,  1.04s/it]

Got Errors {'c5e768e6a0ca063ebb32f3142f2fbd17324e96cb': 'Key c5e768e6a0ca063ebb32f3142f2fbd17324e96cb not found in /da5_fast/All.sha1c/commit_69.tch'}

 23%|██▎       | 778/3314 [13:31<43:56,  1.04s/it]

Got Errors {'d269734888b9bbe2344b6b285ea832b7417f2e16': 'Key d269734888b9bbe2344b6b285ea832b7417f2e16 not found in /da5_fast/All.sha1c/commit_82.tch'}

 27%|██▋       | 879/3314 [15:16<42:10,  1.04s/it]

Got Errors {'edce84f4c552cf1c1d4adcf7a767b4976efebdf4': 'Key edce84f4c552cf1c1d4adcf7a767b4976efebdf4 not found in /da5_fast/All.sha1c/commit_109.tch'}

 27%|██▋       | 905/3314 [15:43<41:44,  1.04s/it]

Got Errors {'f4b03cf66effa48cf370c52f533e6ff97decef28': 'Key f4b03cf66effa48cf370c52f533e6ff97decef28 not found in /da5_fast/All.sha1c/commit_116.tch'}

 28%|██▊       | 926/3314 [16:05<41:30,  1.04s/it]

Got Errors {'f98274201591a5636edef6a8bd33f6e287f19220': 'Key f98274201591a5636edef6a8bd33f6e287f19220 not found in /da5_fast/All.sha1c/commit_121.tch'}

 82%|████████▏ | 2726/3314 [47:21<10:11,  1.04s/it]

Got Errors {'c782ef21e45ac10f0073d3e530ab525e2ba50128': 'Key c782ef21e45ac10f0073d3e530ab525e2ba50128 not found in /da5_fast/All.sha1c/commit_71.tch'}

 90%|█████████ | 2983/3314 [51:51<05:44,  1.04s/it]

Got Errors {'94a7a4f3ff82406d8a3b5cea2b497720c790e77f': 'Key 94a7a4f3ff82406d8a3b5cea2b497720c790e77f not found in /da5_fast/All.sha1c/commit_20.tch'}

 92%|█████████▏| 3056/3314 [53:07<04:28,  1.04s/it]

Got Errors {'beab36622594addc450b50aa7952506f1c5f00ea': 'Key beab36622594addc450b50aa7952506f1c5f00ea not found in /da5_fast/All.sha1c/commit_62.tch'}

 96%|█████████▋| 3192/3314 [55:29<02:06,  1.04s/it]

retrying after error:

 97%|█████████▋| 3204/3314 [55:51<02:00,  1.10s/it]

Got Errors {'02b64f98031e3b704e479a8e223165a1bc15c7d9': 'Key 02b64f98031e3b704e479a8e223165a1bc15c7d9 not found in /da5_fast/All.sha1c/commit_2.tch'}

 97%|█████████▋| 3206/3314 [55:53<01:55,  1.07s/it]

Got Errors {'07af7c851c947faff2efd9f02774293c30d88f4b': 'Key 07af7c851c947faff2efd9f02774293c30d88f4b not found in /da5_fast/All.sha1c/commit_7.tch'}

 97%|█████████▋| 3209/3314 [55:56<01:50,  1.05s/it]

Got Errors {'0e8ba3433087fc412c947bd32b3fb1346abf0dcd': 'Key 0e8ba3433087fc412c947bd32b3fb1346abf0dcd not found in /da5_fast/All.sha1c/commit_14.tch'}

 97%|█████████▋| 3211/3314 [55:58<01:47,  1.05s/it]

Got Errors {'1099bc41cae70a9a071337a72d53fd0291aa1ce4': 'Key 1099bc41cae70a9a071337a72d53fd0291aa1ce4 not found in /da5_fast/All.sha1c/commit_16.tch'}

 97%|█████████▋| 3219/3314 [56:07<01:38,  1.04s/it]

Got Errors {'217532c53217f1073bff1df6f537e736287244f7': 'Key 217532c53217f1073bff1df6f537e736287244f7 not found in /da5_fast/All.sha1c/commit_33.tch'}

 97%|█████████▋| 3221/3314 [56:09<01:36,  1.04s/it]

Got Errors {'27490951336a84c8cf225fbbcc8c3c1b7e9dfb45': 'Key 27490951336a84c8cf225fbbcc8c3c1b7e9dfb45 not found in /da5_fast/All.sha1c/commit_39.tch'}

 97%|█████████▋| 3222/3314 [56:10<01:35,  1.04s/it]

Got Errors {'281ae143b2a64498c27cc757444c6dde79489c7b': 'Key 281ae143b2a64498c27cc757444c6dde79489c7b not found in /da5_fast/All.sha1c/commit_40.tch'}

 97%|█████████▋| 3225/3314 [56:13<01:32,  1.04s/it]

Got Errors {'325816af4ecd90daf28e479b8d3f6d0e75b1531f': 'Key 325816af4ecd90daf28e479b8d3f6d0e75b1531f not found in /da5_fast/All.sha1c/commit_50.tch', '327f5348199891bc1f8b31cdd3682b82baa1f5e5': 'Key 327f5348199891bc1f8b31cdd3682b82baa1f5e5 not found in /da5_fast/All.sha1c/commit_50.tch'}

 98%|█████████▊| 3232/3314 [56:20<01:25,  1.04s/it]

Got Errors {'415bcfe14d36280891d77839955d0cff8a92e41c': 'Key 415bcfe14d36280891d77839955d0cff8a92e41c not found in /da5_fast/All.sha1c/commit_65.tch'}

 98%|█████████▊| 3233/3314 [56:21<01:24,  1.04s/it]

Got Errors {'44e9d862cdccebf05da131205d30949a08fa2254': 'Key 44e9d862cdccebf05da131205d30949a08fa2254 not found in /da5_fast/All.sha1c/commit_68.tch'}

 98%|█████████▊| 3236/3314 [56:24<01:21,  1.04s/it]

Got Errors {'49787d37455044669bac691eb4fe2e77f57df34a': 'Key 49787d37455044669bac691eb4fe2e77f57df34a not found in /da5_fast/All.sha1c/commit_73.tch'}

 98%|█████████▊| 3237/3314 [56:26<01:20,  1.04s/it]

Got Errors {'4adea109050d2e0d7d512bd834a04c239e2d5e41': 'Key 4adea109050d2e0d7d512bd834a04c239e2d5e41 not found in /da5_fast/All.sha1c/commit_74.tch'}

 98%|█████████▊| 3240/3314 [56:29<01:16,  1.04s/it]

Got Errors {'53391413853ba8666895cebb96caf4c12d9540b8': 'Key 53391413853ba8666895cebb96caf4c12d9540b8 not found in /da5_fast/All.sha1c/commit_83.tch'}

 98%|█████████▊| 3251/3314 [56:40<01:05,  1.04s/it]

Got Errors {'6a910bc314ae413f7afd5dfe40620c39bca0fa13': 'Key 6a910bc314ae413f7afd5dfe40620c39bca0fa13 not found in /da5_fast/All.sha1c/commit_106.tch'}

 98%|█████████▊| 3252/3314 [56:41<01:04,  1.04s/it]

Got Errors {'6fc6df0a8b1f1ee296ac3f48b7ddaa49b47c08d6': 'Key 6fc6df0a8b1f1ee296ac3f48b7ddaa49b47c08d6 not found in /da5_fast/All.sha1c/commit_111.tch'}

 98%|█████████▊| 3253/3314 [56:42<01:03,  1.04s/it]

Got Errors {'70bb69bc8d5455ea9eb80a037936d3bab53ea98e': 'Key 70bb69bc8d5455ea9eb80a037936d3bab53ea98e not found in /da5_fast/All.sha1c/commit_112.tch'}

 98%|█████████▊| 3256/3314 [56:45<01:00,  1.04s/it]

Got Errors {'77cc806a6d3130561e937f641962dc8f73b4a4c6': 'Key 77cc806a6d3130561e937f641962dc8f73b4a4c6 not found in /da5_fast/All.sha1c/commit_119.tch'}

 98%|█████████▊| 3259/3314 [56:48<00:57,  1.04s/it]

Got Errors {'82077460b9cf3282d7ec103944e0659c3f34f79a': 'Key 82077460b9cf3282d7ec103944e0659c3f34f79a not found in /da5_fast/All.sha1c/commit_2.tch'}

 99%|█████████▊| 3267/3314 [56:57<00:48,  1.04s/it]

Got Errors {'96b8ca42e10b1a4e60af82bfd819eb1b148561c2': 'Key 96b8ca42e10b1a4e60af82bfd819eb1b148561c2 not found in /da5_fast/All.sha1c/commit_22.tch', '975546439297c7876826ff5c06a70fe6edaf44d5': 'Key 975546439297c7876826ff5c06a70fe6edaf44d5 not found in /da5_fast/All.sha1c/commit_23.tch'}

 99%|█████████▊| 3272/3314 [57:02<00:43,  1.04s/it]

Got Errors {'a3ec6b9ef0ed65ed7a87da5c4dd150eeea516564': 'Key a3ec6b9ef0ed65ed7a87da5c4dd150eeea516564 not found in /da5_fast/All.sha1c/commit_35.tch'}

 99%|█████████▉| 3278/3314 [57:08<00:37,  1.04s/it]

Got Errors {'b016e3439b486de1dc4cc482b4e8901e153adc8b': 'Key b016e3439b486de1dc4cc482b4e8901e153adc8b not found in /da5_fast/All.sha1c/commit_48.tch'}

 99%|█████████▉| 3279/3314 [57:09<00:36,  1.04s/it]

Got Errors {'b2c00e8f85aef734f6d22748795212aac0ddd5aa': 'Key b2c00e8f85aef734f6d22748795212aac0ddd5aa not found in /da5_fast/All.sha1c/commit_50.tch'}

 99%|█████████▉| 3280/3314 [57:10<00:35,  1.04s/it]

Got Errors {'b309d0c59f43682716af673eec55c55c1615216f': 'Key b309d0c59f43682716af673eec55c55c1615216f not found in /da5_fast/All.sha1c/commit_51.tch'}

 99%|█████████▉| 3287/3314 [57:18<00:28,  1.04s/it]

Got Errors {'c4304a921ce2a77483074d1ddd4c05f48220f6b1': 'Key c4304a921ce2a77483074d1ddd4c05f48220f6b1 not found in /da5_fast/All.sha1c/commit_68.tch'}

 99%|█████████▉| 3292/3314 [57:23<00:22,  1.04s/it]

Got Errors {'d258177eb368c5c1821ece1465dc554b774ce7b5': 'Key d258177eb368c5c1821ece1465dc554b774ce7b5 not found in /da5_fast/All.sha1c/commit_82.tch'}

 99%|█████████▉| 3293/3314 [57:24<00:21,  1.04s/it]

Got Errors {'d387afab7574a171a764bf2a3ef62ae7d4aa1cad': 'Key d387afab7574a171a764bf2a3ef62ae7d4aa1cad not found in /da5_fast/All.sha1c/commit_83.tch'}

 99%|█████████▉| 3295/3314 [57:26<00:19,  1.04s/it]

Got Errors {'d9e7240806995f68c547c1f2a136e11004a884be': 'Key d9e7240806995f68c547c1f2a136e11004a884be not found in /da5_fast/All.sha1c/commit_89.tch'}

100%|█████████▉| 3300/3314 [57:31<00:14,  1.04s/it]

Got Errors {'e4334ac14b3dbefb853005a38388f4fa4fbec0b7': 'Key e4334ac14b3dbefb853005a38388f4fa4fbec0b7 not found in /da5_fast/All.sha1c/commit_100.tch'}

100%|█████████▉| 3301/3314 [57:32<00:13,  1.04s/it]

Got Errors {'e65a2603d29e820f816c9a8a3fd39054ef1abb34': 'Key e65a2603d29e820f816c9a8a3fd39054ef1abb34 not found in /da5_fast/All.sha1c/commit_102.tch'}

100%|█████████▉| 3310/3314 [57:41<00:04,  1.04s/it]

Got Errors {'f950f900921a3023381bd9d8998b74d39234040e': 'Key f950f900921a3023381bd9d8998b74d39234040e not found in /da5_fast/All.sha1c/commit_121.tch'}

100%|█████████▉| 3312/3314 [57:44<00:02,  1.04s/it]

Got Errors {'fc3857fba4ba2d3631095fd1c0ef9e03d89ab69a': 'Key fc3857fba4ba2d3631095fd1c0ef9e03d89ab69a not found in /da5_fast/All.sha1c/commit_124.tch'}

100%|██████████| 3314/3314 [57:46<00:00,  1.05s/it]

retrieved 33081 of 33140 unique commits; missing: 59

In [12]:
# flatten: commit = [tree, [parents], [author, unixtime, tz], [committer, unixtime, tz], message]
commit_data = []
for sha, commit in commit_content.items():
    commit_data.append({
        'commit': sha,
        'tree': commit[0],
        'parent': list(commit[1]),
        'author': commit[2][0],
        'author_time': int(commit[2][1]),
        'author_tz': commit[2][2],
        'committer': commit[3][0],
        'committer_time': int(commit[3][1]),
        'committer_tz': commit[3][2],
        'message': commit[4],
    })
df_commit_data = pd.DataFrame(commit_data).merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)
print(commit_data[0])
df_commit_data.head(2)

{'commit': '0001654c779c4bffe0ab685c2b1fc498410fed61', 'tree': 'fae0a5eec0d4a33528115c2b3bcc107c58ff0ee4', 'parent': ['220a17cfa35a14e0ac3e9ce2b88728dcb34c09b7'], 'author': 'Piyush Gautam <gautampiyus@gmail.com>', 'author_time': 1581595380, 'author_tz': '+0530', 'committer': 'GitHub <noreply@github.com>', 'committer_time': 1581595380, 'committer_tz': '+0200', 'message': "Make the legends interactive in bokeh (#1024)\n\n* Made the legends interactive\r\n\r\n* Changed the position of legend to top\r\n\r\n* Added interactive legends to plots energy, ess, kde\r\n\r\n* linting changes\r\n\r\n* final changes\r\n\r\n* Minor changes\r\n\r\n* sphinx error correction\r\n\r\n* minor changes\r\n\r\n* Changes\r\n\r\n* corrected the sphinx error\r\n\r\n* fixed the return axes/glyph issue\r\n\r\n* fixed minor errors\r\n\r\n* added the change to changelog\r\n\r\n* corrected the change to changelog\r\n\r\n* removed the kwargs 'legend' and 'label' from bokeh backend\r\n\r\n* optimized the code using defaultdict and changed the changelog\r\n\r\n* corrected the linting errors\r\n"}

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,0001654c779c4bffe0ab685c2b1fc498410fed61,fae0a5eec0d4a33528115c2b3bcc107c58ff0ee4,[220a17cfa35a14e0ac3e9ce2b88728dcb34c09b7],Piyush Gautam <gautampiyus@gmail.com>,1581595380,+0530,GitHub <noreply@github.com>,1581595380,+0200,Make the legends interactive in bokeh (#1024)\...,0001654c779c4bffe0ab685c2b1fc498410fed61,arviz-devs_arviz
1,000336440e29a42381d1dd7bf37b8fe62ad9f1bc,18e365fd3fc6c32041665a0986912c7ecd99aaa3,[692e46efd58687076204852366c13e33c4bbc57a],Oriol (ZBook) <oriol.abril.pla@gmail.com>,1637788645,+0200,Oriol (ZBook) <oriol.abril.pla@gmail.com>,1639106173,+0200,always copy kwargs dict inplace\n,000336440e29a42381d1dd7bf37b8fe62ad9f1bc,arviz-devs_arviz

## Step 3 — write aamphone_project_summary.csv
One row per (project, commit). The project column comes from each commit's own project (the template reused the loop variable `prj`, which would label every row with the last project). The file is written once in `w` mode so re-running the cell does not duplicate rows.

In [13]:
dfinf = df_commit_data[['project', 'commit', 'author', 'author_time', 'message']].rename(columns={'author_time': 'time'})
dfinf = dfinf.sort_values(['project', 'time']).reset_index(drop=True)
dfinf.to_csv(netid + '_project_summary.csv', index=False, sep=';', mode='w', header=False)
dfinf.head(1)

,project,commit,author,time,message
0,arviz-devs_arviz,9698e0a4595cc242ce571b2908adc78afdea738b,Thomas Wiecki <thomas.wiecki@gmail.com>,1438170670,Initial commit\n

## Step 4 — WoC statistics per project

In [14]:
woc_stats = dfinf.groupby('project').agg(
    ncommits=('commit', 'nunique'),
    nauthors=('author', 'nunique'),
    min_time=('time', 'min'),
    max_time=('time', 'max'),
)
woc_stats['from'] = pd.to_datetime(woc_stats['min_time'], unit='s').dt.strftime('%Y-%m-%d')
woc_stats['to'] = pd.to_datetime(woc_stats['max_time'], unit='s').dt.strftime('%Y-%m-%d')
woc_stats

,ncommits,nauthors,min_time,max_time,from,to
project,,,,,,
arviz-devs_arviz,9492,395,1438170670,1761135327,2015-07-29,2025-10-22
clindatsci_dicomweb-python-client,518,39,1521487507,1757491841,2018-03-19,2025-09-10
flyaflya_causact,457,21,1524067862,1757705466,2018-04-18,2025-09-12
genouest_biomaj-download,505,19,1472208351,1750133502,2016-08-26,2025-06-17
geolytix_xyz,15306,65,1512569316,1762277501,2017-12-06,2025-11-04
kkondo1981_aglm,366,6,1546232994,1746979099,2018-12-31,2025-05-11
nbara_python-meegkit,479,45,1227075592,1775048948,2008-11-19,2026-04-01
peal_vole,595,7,1395418492,1757678214,2014-03-21,2025-09-12
pressio_pressio,4282,52,1525121445,1757514162,2018-04-30,2025-09-10
winvector_vtreat,1081,6,1407432287,1736461287,2014-08-07,2025-01-09

## GitHub data (collected 2026-10-07)
Stars and forks as displayed on each repository page (GitHub rounds counts above 1,000, so arviz shows 1.8k). Last commit date is the newest commit on the default branch.

| Project | GitHub repo | Stars | Forks | Last commit date |
|---|---|---|---|---|
| arviz-devs_arviz | arviz-devs/arviz | 1.8k | 501 | 2026-09-09 |
| clindatsci_dicomweb-python-client | clindatsci/dicomweb-python-client (now redirects to ImagingDataCommons/dicomweb-client) | 129 | 42 | 2026-08-17 |
| peal_vole | peal/vole | 8 | 2 | 2026-07-01 |
| nbara_python-meegkit | nbara/python-meegkit | 227 | 57 | 2026-08-21 |
| flyaflya_causact | flyaflya/causact | 47 | 12 | 2025-09-12 |
| geolytix_xyz | GEOLYTIX/xyz | 132 | 44 | 2026-10-02 |
| genouest_biomaj-download | genouest/biomaj-download | 1 | 7 | 2025-05-20 |
| pressio_pressio | Pressio/pressio (default branch: develop) | 50 | 7 | 2025-09-10 |
| kkondo1981_aglm | kkondo1981/aglm | 17 | 5 | 2025-05-12 |
| winvector_vtreat | WinVector/vtreat | 284 | 45 | 2025-01-09 |

## WoC data
(Fill in from the `woc_stats` table above: number of commits, number of authors, min time, max time.)

# Make sure you check in to your fork not just the notebook but also the csv files!!!

In [15]:
import pandas as pd
from google.colab import files

rows = []
for prj, sha in zip(df['project'], df['sha1']):
    c = commit_content.get(sha)
    if c is not None:
        rows.append((prj, sha, c[2][0], int(c[2][1]), c[4]))
summary = pd.DataFrame(rows).sort_values([0, 3])
summary.to_csv('aamphone_project_summary.csv', sep=';', header=False, index=False)
print(len(summary), 'rows written')
files.download('aamphone_project_summary.csv')

33081 rows written